CREATE DATABASE ecommerce_project;
USE ecommerce_project;
SELECT DATABASE();

CREATE TABLE customers(
customer_id INT PRIMARY KEY,
customer_name VARCHAR (100),
gender VARCHAR(10),
city VARCHAR(100),
singup_date date);

CREATE TABLE products( 
product_id INT PRIMARY KEY,
product_name VARCHAR (100),
category VARCHAR (50),
price DECIMAL(10,2)
);

CREATE TABLE orders(
order_id INT PRIMARY KEY,
customer_id INT,
order_date DATE,
order_status VARCHAR(30),
FOREIGN KEY (customer_id)references
customers(customer_id)
);
CREATE TABLE order_items(
order_items_id INT PRIMARY KEY,
order_id INT ,
product_id INT,
quantity INT ,
unit_price DECIMAL (10,2),
FOREIGN KEY (order_id) references
orders(order_id),
FOREIGN KEY (product_id)references
products(product_id)
);
INSERT INTO customers VALUES
(1,'Rahul','Male','Mumbai','2025-01-10'),
(2,'Priya','Female','Delhi','2025-02-01'),
(3,'Amit','Male','pune','2025-02-01'),
(4,'Sneha','Female','Bangalore','2025-02-10'),
(5,'Eohan','Male','Hyederabad','2025-03-05');
INSERT INTO products VALUES
(101,'Laptop','Electronics',65000),
(102,'Headphones','Electronics',2500),
(103,'Office Chair','Furniture',7000),
(104,'Keyboard','Electronics',1800),
(105,'Water Bottle','Home',600);

INSERT INTO orders VALUES
(1001,1,'2025-03-01','Delivered'),
(1002,2,'2025-03-03','Delivered'),
(1003,3,'2025-03-10','Delivered'),
(1004,4,'2025-03-15','Cancelled'),
(1005,3,'2025-03-20','Delivered');

INSERT INTO order_items VALUES
(1,1001,101,1,65000),
(2,1001,102,2,2500),
(3,1002,103,1,7000),
(4,1003,104,1,1800),
(5,1004,105,3,600),
(6,1005,101,1,65000);

SHOW TABLES;

/*BUSINESS QUESTIONS*/

/*Question 1: Calculate the total revenue*/
SELECT SUM(quantity* unit_price) AS total_revenue
FROM order_items;

/*Question 2: Count Total Orders*/
SELECT COUNT(*) AS total_orders
FROM orders;

/*Question 3: Count Total Customers*/
SELECT COUNT(*) AS Total_customers
FROM customers;

/*Question 4: Count Total Products*/
SELECT COUNT(*) AS total_products
FROM products;

/*Question 5: Calculate The Average Order value*/
WITH average_order_value AS 
(SELECT order_id,
SUM(quantity * unit_price) AS order_value
FROM order_items
GROUP BY order_id)
SELECT ROUND( AVG(order_value),2) AS average_order_value
FROM average_order_value;

/*Question 6: Find The Top 5 Selling Products*/

SELECT products.product_id,      
       products.product_name,
       order_items.unit_price,
	   SUM(quantity) AS total_units_sold
FROM products
JOIN order_items
ON products.product_id =order_items.product_id
GROUP BY products.product_id,
         products.product_name,
         order_items.unit_price
ORDER BY total_units_sold DESC
LIMIT 5;

/*Finding:
 The query identifies the five products with the highest total units sold across all orders.

Business insight:
 These products are the company's best sellers. The business should prioritize keeping them in stock,
monitor inventory levels closely, and consider promoting complementary products to increase revenue. 
Understanding top-selling products also helps with demand forecasting and purchasing decisions.*/

/*Question 7: Find The Revenue By Product Category */
SELECT products.category,
       SUM(quantity * unit_price) AS total_revenue
FROM products
JOIN order_items
ON products.product_id =order_items.product_id
GROUP BY products.category
ORDER BY total_revenue DESC;

/*Finding
The query calculates the total revenue generated by each product category.

Business insight
Electronics generated the highest revenue, indicating that it is the company's strongest-performing category. 
The business should ensure sufficient inventory, continue marketing these products, 
and explore opportunities to expand the electronics product range. 
Lower-performing categories such as Home may require promotional campaigns or pricing strategies to increase sales.*/

/*Question 8: Find Top 5 Customers by revenue*/
SELECT customers.customer_name,
       customers.customer_id,
       SUM(quantity *unit_price) AS revenue
FROM customers
JOIN orders
   ON customers.customer_id = orders.customer_id
JOIN order_items
   ON orders.order_id = order_items.order_id
GROUP BY customers.customer_name,
         customers.customer_id
ORDER BY revenue DESC
LIMIT 5;

/* Finding: 
The query ranks customers by the total revenue they generated from their purchases. 
Based on the available data, only 4 customers have placed orders, 
so the results include all customers with purchase history, ranked from highest to lowest revenue.

Business Insight: 
Rahul generated the highest revenue because he placed multiple orders,
making him a valuable customer for retention initiatives such as loyalty rewards or personalized promotions. 
Amit, Priya, and Sneha also contributed to revenue, while Eohan has not placed any orders. 
The business could target customers like Eohan with welcome offers, discounts, or 
marketing campaigns to encourage their first purchase.*/

/*Question 9: Calculate monthly revenue */

SELECT 
       SUM(quantity * unit_price) AS revenue,
       MONTH(order_date) AS month
FROM orders
JOIN order_items
ON orders.order_id = order_items.order_id
GROUP BY month
ORDER BY month;

/* Finding: 
The query calculates the total revenue generated in each month by summing the revenue (quantity × unit_price) of all order items. 
The results provide a month-by-month summary of sales performance.
All orders occurred in March 2025, so the report shows revenue for only one month(March).

Business Insight:
March generated all of the recorded revenue in the dataset, indicating that the available data covers a single month of sales. 
As more months of data are collected, this report can be used to identify seasonal trends, compare month-over-month performance, 
forecast future sales, and evaluate the effectiveness of marketing campaigns or promotions. */

/*Question 10: Find Revenue by city */
SELECT customers.city,
       SUM(quantity * unit_price) AS revenue
FROM customers
JOIN orders
ON customers.customer_id = orders.customer_id
JOIN order_items
ON orders.order_id=order_items.order_id
GROUP BY city
ORDER BY revenue DESC;
 
 /*Finding: 
 The query calculates the total revenue generated by customers from each city 
 by summing the value of all purchased items (quantity × unit_price). 
 The results rank cities from the highest to the lowest revenue.

Business Insight: 
Cities generating the highest revenue represent the company's strongest markets. 
The business can prioritize these locations for marketing campaigns, inventory planning, and customer retention initiatives. 
Cities with lower revenue may benefit from targeted promotions, localized advertising, 
or special offers to stimulate sales and increase market penetration. */

/*Question 11: Find repeat customers */

SELECT COUNT(order_id) AS order_count,
       customers.customer_id,
       customers.customer_name
FROM orders
JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_name,
         customers.customer_id
HAVING order_count >1;

/*Finding: 
The query identifies customers who have placed more than one order. 
In the current dataset, only Amit qualifies as a repeat customer, having placed 2 orders.

Business Insight:
Repeat customers are valuable because they demonstrate loyalty and contribute recurring revenue. 
Amit has made multiple purchases, making them a good candidate for loyalty rewards, personalized promotions, or exclusive offers. 
Encouraging one-time customers to become repeat customers can increase customer lifetime value and improve long-term business growth.
 */
 
 /*Question 12: Find Customers Who Never Placed An Order */
 
 SELECT customers.customer_name,
        customers.customer_id,
        orders.order_id
FROM customers
LEFT JOIN orders
ON customers.customer_id = orders.customer_id
WHERE orders.order_id IS NULL;

/*Finding: 
The query identifies customers who have never placed an order. 
In the current dataset, Eohan has not made any purchases and therefore does not appear in the orders table.

Business Insight:
Customers who have never placed an order represent potential growth opportunities. 
The business can target these customers with welcome discounts, personalized email campaigns, 
or first-purchase incentives to encourage them to complete their first order and increase customer conversion.*/

/*Question 13: Find Inactive Customers(No Orders In The last 90 Days)*/

SELECT customers.customer_id,
       customers.customer_name,
       MAX(order_date) AS latest_order_date
FROM customers
LEFT JOIN orders
ON customers.customer_id = orders.customer_id
GROUP BY  customers.customer_name,
          customers.customer_id
HAVING MAX(order_date) < DATE_SUB(CURDATE(), INTERVAL 90 DAY);  

/*Finding: 
The analysis identifies both customers whose latest order was more than 90 days ago and 
customers who have never placed an order. 
These groups represent inactive customers requiring different engagement strategies.

Business Insight:
Customers who have never purchased may respond well to welcome offers or first-order discounts, 
while previously active customers may be encouraged to return through personalized recommendations, loyalty incentives, or reactivation campaigns. 
Segmenting these groups allows the business to create more effective marketing campaigns.*/

/* Question 14: Find The Best selling product category */

SELECT products.category,
      SUM(quantity * unit_price) AS revenue
FROM order_items
JOIN products
ON order_items.product_id = products.product_id
GROUP BY products.category
ORDER BY revenue DESC
LIMIT 1;

/*Finding: 
Electronics generated the highest total revenue among all product categories, making it the best-selling category in the dataset.

Business Insight: 
Since Electronics contributes the most revenue, the business should prioritize stock availability, 
introduce complementary products through cross-selling, and invest in targeted promotions to maximize sales. 
At the same time, lower-performing categories should be reviewed to identify opportunities for growth through pricing strategies, 
product assortment, or marketing initiatives.*/

/* Question 15: Find the highest revenue product */
SELECT products.product_name,
       SUM(quantity * unit_price) AS highest_revenue
FROM products
JOIN order_items
ON products.product_id = order_items.product_id
GROUP BY products.product_name
ORDER BY highest_revenue DESC
LIMIT 1;

/* Finding: 
The Laptop generated the highest total revenue among all products, making it the top revenue-generating product in the dataset.

Business Insight: 
The highest revenue-generating product is a key contributor to the company's overall sales performance. 
The business should ensure this product remains well-stocked, monitor inventory closely, and feature it in marketing campaigns. 
The company can also increase revenue by recommending complementary products (cross-selling) or premium alternatives (upselling) alongside this product. */

/*Question 16: Find the lowest revenue product */
SELECT products.product_name,
       SUM(quantity * unit_price) AS lowest_revenue
FROM products
JOIN order_items
ON products.product_id = order_items.product_id
GROUP BY products.product_name
ORDER BY lowest_revenue ASC
LIMIT 1;       

/*Finding: 
The Keyboard generated the lowest total revenue among all products in the dataset.

Business Insight: The lowest revenue-generating product may indicate low customer demand, ineffective pricing, 
or limited sales volume. The business should evaluate whether the product requires additional marketing, promotional discounts, or repositioning. 
If the product consistently underperforms, 
the company may consider reducing inventory levels or replacing it with products that better meet customer demand.*/

/* Question 17:Calculate average products per order */
WITH order_totals AS(
                   SELECT order_id,
                          SUM(quantity) AS total_products
					FROM order_items
                    GROUP BY order_id)
SELECT AVG(total_products) AS average_products_per_order
FROM order_totals;             

/*Finding: The analysis calculates the average number of product units purchased per order by first summing the quantities for each order and 
then averaging those totals across all orders. 
This provides insight into the typical order size.       

Business Insight: 
The average number of products purchased per order helps the business understand customer purchasing behavior. 
If the average is relatively low, the company can increase order sizes by introducing product bundles, cross-selling complementary items, 
or offering discounts for purchasing multiple products. 
Increasing the average products per order can improve overall revenue without needing to acquire additional customers.

/*Question 18: Find orders worth more than 10000 */
SELECT 	order_id,
        SUM(quantity * unit_price) AS order_value
FROM order_items
GROUP BY order_id
HAVING order_value > 10000;

/*Finding: 
The query identifies all orders with a total value exceeding 10,000 by calculating the total revenue (quantity × unit_price) for each order. 
These orders represent high-value purchases that contribute significantly to the company's total revenue.

Business Insight: 
High-value orders have a substantial impact on overall sales performance. 
The business should identify the customers behind these purchases to understand their buying behavior and 
strengthen relationships through loyalty programs, premium customer support, or personalized offers. 
Analyzing these orders can also help identify popular high-value products and sales opportunities.*/

/*Question 19: Find customers with the  highest average order value */

WITH order_values AS (SELECT 
                             SUM(quantity * unit_price) AS order_value,
							 orders.order_id,
                             orders.customer_id
                             FROM order_items
                             JOIN orders
                             ON order_items.order_id = orders.order_id
                             GROUP BY orders.order_id,
                                      orders.customer_id
)
SELECT customers.customer_name,
AVG(order_value) AS average_order_value
FROM order_values
JOIN customers
ON order_values.customer_id = customers.customer_id
GROUP BY customers.customer_name
ORDER BY average_order_value DESC
LIMIT 1;

